version: "3"
services:
  dev_db:
    image: postgres:alpine
    container_name: feedadoc_db
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: feedadoc_development
      POSTGRES_USER: feedadoc
      POSTGRES_PASSWORD: password1
